### ISSUE TITLE
`controlnet_blocks` not used anywhere

### ISSUE THREAD

**Issue by jntesai** [ir-lab/Diff-Control#1]
Trying to understand the net arch to the details and found that `controlnet_blocks` (i.e., the zero conv block) doesn't seem to be used anywhere in the codebase. So the only actual zero conv happens at the bottle neck which is `mid_controlnet_block`?

I guess the intended way of using `controlnet_blocks` is actually applying it to every corresponding `h_hat` right?

**Comment by liuxiao1468** [comment]
> Trying to understand the net arch to the details and found that `controlnet_blocks` (i.e., the zero conv block) doesn't seem to be used anywhere in the codebase. So the only actual zero conv happens at the bottle neck which is `mid_controlnet_block`?
> 
> I guess the intended way of using `controlnet_blocks` is actually applying it to every corresponding `h_hat` right?

Hey sorry for the confusion, I might commit the very initial version of the code and I've fixed this via here https://github.com/ir-lab/Diff-Control/commit/eff827642c1682fba752023b0dacaf24728fbcfb
